version: '3.8'

services:
  nginx:
    image: nginxdemo:v1  # Use the official NGINX image
    container_name: hmsnginx
    ports:
      - "8181:80"  # Expose host port 8181, Nginx listens on container port 80
    volumes:
      - ./nginx-default.conf:/etc/nginx/conf.d/default.conf  # Mount the NGINX config file
    depends_on:
      - doctormanagement
      - adminmanagement
      - usermanagement
      - clinicmanagement
    networks:
      - my-network

  doctormanagement:
    image: doctormgmtdemo:v1
    container_name: doctormanagement
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    networks:
      - my-network
    ports:
      - "5003:5003"  # Expose internal port 5003 on external port 5003

  adminmanagement:
    image: adminmgmtdemo:v1
    container_name: adminmanagement
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    networks:
      - my-network
    ports:
      - "5001:5001"  # Expose internal port 5001 on external port 5001
    depends_on:
      - mongodb  # Add MongoDB as a dependency

  usermanagement:
    image: usermgmtdemo:v1
    container_name: usermanagement
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    networks:
      - my-network
    ports:
      - "5004:5004"  # Expose internal port 5004 on external port 5004

  clinicmanagement:
    image: clinicmgmtdemo:v1
    container_name: clinicmanagement
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    networks:
      - my-network
    ports:
      - "5002:5002"  # Expose internal port 5002 on external port 5002

  mongodb:
    image: mongoimage:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db1
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root      # Set the MongoDB root username
      - MONGO_INITDB_ROOT_PASSWORD=password1      # Set the MongoDB root password
      - MONGO_INITDB_DATABASE=HMS            # Specify the database to create
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

volumes:
  mongo_data:

